### ISSUE TITLE
regression: Connections require ToType to implement Node Interface

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#2629]
### Description

When updating to v1.13.0, errors will occur if any connections had been registered by 3rd party code where the toType is a type that does not implement the `Node` interface. 

In v1.13.0 we introduced the Edge and Node interfaces, which require connections to connect _to_ Types that implement the Node interface. 

Extensions such as WPGraphQL for WooCommerce register connections to GraphQL Types that do not implement the `Node` interface, which causes conflicts with the Schema.

### Steps to reproduce

1. Update WPGraphQL to v1.13+
2. Activate WPGraphQL for WooCommerce v0.11.2
3. See errors in GraphiQL, like so:

![CleanShot 2022-11-28 at 20 28 11](https://user-images.githubusercontent.com/1260765/204431599-7f5747ab-1e98-4b29-bf5b-d81864315c74.png)

### Additional context

I'm not sure the best way to handle this other than having extending plugins ensure their toTypes are Nodes, or roll-back the feature 🤔 

If the extending plugins that register connections don't update, we see errors like documented above until their Types are updated to implement the Node interface. 

### WPGraphQL Version

1.13.3

### WordPress Version

6.1

### PHP Version

8.0

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
I don't believe this is actionable for WPGraphQL itself, but extending plugins need to adhere. 

For example, WooCommerce: https://github.com/wp-graphql/wp-graphql-woocommerce/pull/674

**Comment by justlevine** [comment]
> I'm not sure the best way to handle this other than having extending plugins ensure their toTypes are Nodes, or roll-back the feature 🤔
>
> If the extending plugins that register connections don't update, we see errors like documented above until their Types are updated to implement the Node interface.

This is a tough one. The majority of WPGraphQL extensions don't have sponsored maintainers, so who knows how many have had the resources to keep up with the iterating best practices. That said, WPGraphQL has set a precedent for 'breaking' 3rd party plugins when it felt it had to. And in lieu of a concrete roadmap for v2 (i.e. what breaking changes we want to include, and what steps we need to get there), I'm hesitant to suggest we roll back entirely - limiting technically non-breaking improvements because we can't account for the cool but unexpected things that 3rd-party devs are doing is untenable.

Two possible options I havn't fully thought through:

- We could try to only apply the new Connection interfaces on connections registered with the Schema API (and _dont_ have `Node` in $config['graphql_excluded_connections']. In this approach, we'd stop short of implementing the interfaces on the existing connections directly.
- We could try to make the new conne
ctions wholly _additive_. Meaning we drop the `'nodes' => [ 'type' => [ 'list_of' => 'non_null' => 'Node' ] ] `*. In this approach, using these Connection interfaces for querying would become less helpful (since it could only DRY out `edges`, but from my understanding that is more of a side effect of the change, and the primary goal of letting developers _extend_ their connections in a more centralized place is left in tact.

* PS: why was this made `non-null`, what happens if there are no results for the connection?

**Comment by jasonbahl** [comment]
I'm going to mark this resolved as there's now the option to `includeDefaultInterfaces => true/false`
